apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-microservice
  labels:
    app: frontend
    tier: frontend
    environment: production
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 80
  type: LoadBalancer