apiVersion: v1
kind: Service
metadata:
  name: profile-backend
  namespace: mern-microservice
  labels:
    app: profile-backend
    tier: profile-backend
    environment: production
spec:
  selector:
    app: profile-backend
  ports:
  - port: 3002
    targetPort: 3002
  type: LoadBalancer