apiVersion: v1
kind: Service
metadata:
  name: hello-backend
  namespace: mern-microservice
  labels:
    app: hello-backend
    tier: hello-backend
    environment: production
spec:
  selector:
    app: hello-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer