apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-microservice.fullname" . }}-frontend
  labels:
    app: {{ include "mern-microservice.name" . }}-frontend
    tier: {{ include "mern-microservice.name" . }}-frontend
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mern-microservice.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "mern-microservice.name" . }}-frontend
        tier: {{ include "mern-microservice.name" . }}-frontend
        environment: {{ .Values.environment }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ include "mern-microservice.name" . }}-frontend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.containerPort }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}