# The environment (e.g., production, staging, development)
environment: production
nameOverride: "mern-microservice-frontend"
fullnameOverride: "mern-microservice-frontend"

# Docker image settings
image:
  repository: securelooper/mern-microservices-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 2

containerPort: 80
restartPolicy: Always

# Kubernetes Service for the frontend
service: 
  type: LoadBalancer
  port: 3000
  targetPort: 80
  
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 40
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 2